=== djgonza/LMGI/UT3/XML/Actividad 6/socios.dtd
<!ELEMENT sociedad (socio)+>
	<!ELEMENT socio (socio_iden,telefonoFijo?,telefonoMovil+,edad,fechaingreso,empadronado?)>
		<!ELEMENT socio_iden (situacion?,nombre_socio,mail+)>
		<!ATTLIST socio num ID #REQUIRED>
			<!ELEMENT situacion (paro|trabajador)>
			<!-- Meses que lleva en paro o Nombre de la empresa si es trabajador -->
				<!ELEMENT paro (#PCDATA)>
				<!ELEMENT trabajador (#PCDATA)>
			<!ELEMENT nombre_socio (nombre,apellido)>
				<!ELEMENT nombre (#PCDATA)>
				<!ELEMENT apellido (#PCDATA)>
				<!ATTLIST nombre_socio apodo NMTOKEN #REQUIRED>
			<!ELEMENT mail (#PCDATA)>
		<!ELEMENT telefonoFijo (#PCDATA)>
		<!ELEMENT telefonoMovil (#PCDATA)>
		<!ELEMENT edad (#PCDATA)>
		<!ELEMENT fechaingreso (#PCDATA)>
			<!ENTITY fechaIngreso "La fecha de ingreso es ">
		<!ELEMENT empadronado EMPTY>
			<!ATTLIST empadronado sit (si|no) #REQUIRED>

=== djgonza/LMGI/UT3/XML/Actividad 6/socios.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE sociedad SYSTEM "socios.dtd" [
	<!ENTITY fechaIngreso "La fecha de ingreso es ">
]>

<sociedad>
    <socio num="U-01">
    	<socio_iden>
	        <situacion>
	            <paro />
	        </situacion>
	        <nombre_socio apodo="chd">
	            <nombre>
	                Pepe
	            </nombre>
	            <apellido>
	                Gomez
	            </apellido>
	        </nombre_socio>
	        <mail>pepe@gmail.com</mail>
	    </socio_iden>
        <telefonoFijo>948523658</telefonoFijo>
        <telefonoMovil>563259632</telefonoMovil>	
        <edad>31</edad>
        <fechaingreso>&fechaIngreso; 25/11/2000</fechaingreso>
        <empadronado sit="si" />
    </socio>
    <socio num="U-02">
    	<socio_iden>
	        <situacion>
	            <trabajador />
	        </situacion>
	        <nombre_socio apodo="jkl">
	            <nombre>
	                Sara
	            </nombre>
	            <apellido>
	                Gomez
	            </apellido>
	        </nombre_socio>
	        <mail>sara@gmail.com</mail>
	    </socio_iden>
        <telefonoMovil>654123456</telefonoMovil>	
        <edad>54</edad>
        <fechaingreso>&fechaIngreso; 25/11/1985</fechaingreso>
        <empadronado sit="no" />
    </socio>
    <socio num="U-03">
    	<socio_iden>
	        <situacion>
	            <trabajador />
	        </situacion>
	        <nombre_socio apodo="klo">
	            <nombre>
	                Manuel
	            </nombre>
	            <apellido>
	                Gomez
	            </apellido>
	        </nombre_socio>
	        <mail>manuel@gmail.com</mail>
	    </socio_iden>
        <telefonoMovil>654586586</telefonoMovil>	
        <edad>24</edad>
        <fechaingreso>&fechaIngreso; 25/11/1985</fechaingreso>
        <empadronado sit="no" />
    </socio>
</sociedad>
