=== djgonza/LMGI/UT3/XML/Schema/Actividad 3/revista.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    
    <xs:complexType name="datospersonales">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellido" type="xs:string"/>
            <xs:element name="telefono" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    
    <xs:element name="revista">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="editor" type="datospersonales"/>
                <xs:element name="fechapublicacion" type="xs:date"/>
                <xs:element name="articulo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="autor" type="datospersonales"/>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="numeropalabras" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="numref" type="xs:integer" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== djgonza/LMGI/UT3/XML/Schema/Actividad 3/revista.xml
<?xml version="1.0" encoding="UTF-8"?>

<revista
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='revista.xsd' >
    
    <editor>
        <nombre>Manolo</nombre>
        <apellido>Gomez</apellido>
        <telefono>64587788</telefono>
    </editor>
    <fechapublicacion>2005-03-03</fechapublicacion>
    <articulo>
        <autor>
            <nombre>Gorka</nombre>
            <apellido>Van Gohg</apellido>
            <telefono>6544112</telefono>
        </autor>
        <titulo>La cofradia</titulo>
        <numeropalabras>548</numeropalabras>
    </articulo>
    <articulo>
        <autor>
            <nombre>Leire</nombre>
            <apellido>Eslava</apellido>
            <telefono>698542147</telefono>
        </autor>
        <titulo>La isla</titulo>
        <numeropalabras>541</numeropalabras>
    </articulo>
    <articulo>
        <autor>
            <nombre>Pepe</nombre>
            <apellido>Perez</apellido>
            <telefono>652321477</telefono>
        </autor>
        <titulo>La iliada</titulo>
        <numeropalabras>1000</numeropalabras>
    </articulo>

</revista>
