=== djgonza/LMGI/UT3/XML/DTD/Actividad 7/agenda/agendadtd.dtd
<!ELEMENT agenda (contactos*)>
    <!ELEMENT contactos (contacto, direccion, telefono, fecha_nacimiento, email?)>
    <!ELEMENT contacto (nombre, apellido)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
     <!ELEMENT direccion (calle, provincia)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
     <!ELEMENT fecha_nacimiento (año, mes, día)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT día (#PCDATA)>
    <!ELEMENT email (#PCDATA)>

=== djgonza/LMGI/UT3/XML/Actividad 7/agenda/agenda2.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE agenda SYSTEM "agendadtd.dtd">
<agenda >
    <contactos>
        <contacto>
            <nombre>Sara</nombre>
            <apellido>Cale</apellido>
        </contacto>
        <direccion> 
            <calle>C\ eunsasi nÂº10</calle>
            <provincia>Navarra</provincia>
        </direccion>
        <telefono>948523523</telefono>
        <fecha_nacimiento>
            <ano>1991</ano>
            <mes>10</mes>
            <dia>10</dia>
        </fecha_nacimiento>
        <email>sara@gmail.com</email>
    </contactos>
    <contactos>
        <contacto>
            <nombre>Maria</nombre>
            <apellido>Gomez</apellido>
        </contacto>
        <direccion> 
            <calle>Avd. Mi casa</calle>
            <provincia>Navarra</provincia>
        </direccion>
        <telefono>948523698</telefono>
        <fecha_nacimiento>
            <ano>1922</ano>
            <mes>01</mes>
            <dia>07</dia>
        </fecha_nacimiento>
    </contactos>
    <contactos>
        <contacto>
            <nombre>Manolo</nombre>
            <apellido>Garcia</apellido>
        </contacto>
        <direccion> 
            <calle>Avenida Bayona</calle>
            <provincia>Navarra</provincia>
        </direccion>
        <telefono>948458965</telefono>
        <fecha_nacimiento>
            <ano>1952</ano>
            <mes>11</mes>
            <dia>07</dia>
        </fecha_nacimiento>
        <email>manolo@hotmail.com</email>
    </contactos>
</agenda>
