=== djgonza/LMGI/UT3/XML/Schema/Invento/inventor.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
   
    <xs:complexType name="cthistoria">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="filas" type="xs:integer" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="ctpatentado">
        <xs:attribute name="valor" type="xs:string" default="si" />
    </xs:complexType>
    
    <xs:complexType name="ctarchivado" mixed="true">
        <xs:sequence>
            <xs:element name="bibliotecario" type="xs:string" />
            <xs:element name="fecha" type="xs:date" />
        </xs:sequence>
        <xs:attribute name="doc" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ctinventor">
        <xs:sequence>
            <xs:element name="pais" type="xs:string" />
            <xs:element name="fechanacimi" type="xs:date" />
            <xs:element name="historia" type="cthistoria" />
            <xs:element name="archivado" type="ctarchivado" />
            <xs:element name="patentado" type="ctpatentado" />
        </xs:sequence>
        <xs:attribute name="nombre" type="xs:string" use="required"/>
        <xs:attribute name="invento" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="ctinventores">
        <xs:sequence>
            <xs:element name="inventor" maxOccurs="unbounded" type="ctinventor" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="inventores" type="ctinventores"/>
</xs:schema>

=== djgonza/LMGI/UT3/XML/Schema/Invento/inventorXS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<inventores
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='inventor.xsd'>
    <inventor 
        nombre="Robert Adler"
        invento="Mando a distancia">
        <pais>Viena</pais>
        <fechanacimi>1913-12-04</fechanacimi>
        <historia filas="6">
            En 1956, Robert Adler desarrollo el “Zenith Space Command”
            (Mando del espacio cenit), un control sin cables. Era mecánico y
            usaba ultrasonidos para cambiar el canal y el volumen.
            Cuando el usuario pulsaba un botón del mando a distancia, hacía
            un chasquido y golpeaba una barra, de ahí el término para
            denominarlo en EE.UU.“clicker” (chasqueador). Cada barra emitía
            una......
        </historia>
        <archivado doc="RD_154">
            El archivo lo realizó:
            <bibliotecario>Rudolf Treys</bibliotecario>
            En la fecha:
            <fecha>1950-11-25</fecha>
        </archivado>
        <patentado valor="si"/>
    </inventor>
    <inventor 
        nombre="Robert Adler"
        invento="Mando a distancia">
        <pais>Viena</pais>
        <fechanacimi>1913-12-04</fechanacimi>
        <historia filas="6">
            En 1956, Robert Adler desarrollo el “Zenith Space Command”
            (Mando del espacio cenit), un control sin cables. Era mecánico y
            usaba ultrasonidos para cambiar el canal y el volumen.
            Cuando el usuario pulsaba un botón del mando a distancia, hacía
            un chasquido y golpeaba una barra, de ahí el término para
            denominarlo en EE.UU.“clicker” (chasqueador). Cada barra emitía
            una......
        </historia>
        <archivado doc="RD_154">
            El archivo lo realizó:
            <bibliotecario>Rudolf Treys</bibliotecario>
            En la fecha:
            <fecha>1950-11-25</fecha>
        </archivado>
        <patentado valor="si"/>
    </inventor>
</inventores>
