=== djgonza/LMGI/UT3/XML/Schema/Pedido/pedidos.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:group name="groupDatosDireccion">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="calle" type="xs:string" />
            <xs:element name="ciudad" type="xs:string" />
            <xs:element name="estado" type="stEstado" />
            <xs:element name="codigoPostal" type="xs:integer" />
        </xs:sequence>
    </xs:group>
    
     <xs:simpleType name="stEstado">
        <xs:restriction base="xs:string">
            <xs:pattern value="AL | AR | CA | MA | MI" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="ctArticulo">
        <xs:sequence>
            <xs:element name="nombreProducto" type="xs:string" />
            <xs:element name="cantidad" type="stCantidad" />
            <xs:element name="precioEEUU" type="xs:double" />
            <xs:element name="comentario" type="xs:string" minOccurs="0" />
            <xs:element name="fechaEnvio" type="xs:date" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="codigoStock" type="stCodigoStock" />
    </xs:complexType>
    
    <xs:simpleType name="stCantidad">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[1-99]" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="stCodigoStock">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9][-][A-Z][A-Z]" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="ctArticulos">
        <xs:sequence>
            <xs:element name="articulo" type="ctArticulo" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="fechaPedido" type="xs:date" />
    </xs:complexType>
    
    <xs:element name="enviarA">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="groupDatosDireccion" />
            </xs:sequence>
            <xs:attribute name="pais" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="facturarA">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="groupDatosDireccion" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enviarA" />
                <xs:element name="facturarA" />
                <xs:element name="articulos" type="ctArticulos" />
            </xs:sequence>
            <xs:attribute name="fechaPedido" type="xs:date" />
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== djgonza/LMGI/UT3/XML/Schema/Pedido/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>


<pedido fechaPedido="2006-06-22"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='pedidos.xsd'>
    
    <enviarA pais="EEUU">
        <nombre>Alice Smith</nombre>
        <calle>123 Maple Street</calle>
        <ciudad>Cambridge</ciudad>
        <estado>MA</estado>
        <codigoPostal>12345</codigoPostal>
    </enviarA>
    
    <facturarA>
        <nombre>John Bob</nombre>
        <calle>242 Main Street</calle>
        <ciudad>Beverly Hills</ciudad>
        <estado>CA</estado>
        <codigoPostal>90210</codigoPostal>
    </facturarA>
    
    <articulos>
        <articulo codigoStock="872-AA">
            <nombreProducto>Cortacésped</nombreProducto>
            <cantidad>1</cantidad>
            <precioEEUU>148.95</precioEEUU>
            <comentario>Eléctrico con baterías recargables</comentario>
            <fechaEnvio>2006-06-28</fechaEnvio>
        </articulo>
        <articulo codigoStock="926-BC">
            <nombreProducto>Bolsa de tierra de abono marca
                Acme</nombreProducto>
            <cantidad>1</cantidad>
            <precioEEUU>7.20</precioEEUU>
        </articulo>
    </articulos>
    
</pedido>
